

spring:
  datasource:
    url: jdbc:mysql://biom-mysql.ciz1iv3yolly.ap-northeast-2.rds.amazonaws.com:3306/biom_backend_dev
    username: admin
    password: adminroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com:
      biom: debug
    org:
      springframework:
        security: debug


users:
  jwt:
    secret: biomdevrandom
  oauth2:
    google:
      resource-url: https://www.googleapis.com/oauth2/v1/userinfo?alt=json