server:
  port: 8130

  error:
    include-exception: true
    include-message: always
    include-stacktrace: never
spring:
  messages:
    basename: messages, errors


logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul