spring:
  web:
    resources:
      add-mappings: false
  mvc:
    # throws exception when no handlers found for a mapping
    throw-exception-if-no-handler-found: true

  jackson:
    # ignores null fields in serialization
    default-property-inclusion: non_null

  datasource:
    url: jdbc:mysql://localhost:3306/biom
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  config:
    activate:
      on-profile: local

logging:
  level:
    com:
      biom: debug
    org:
      springframework:
        web: debug
        security: debug


    # --- sql 에 들어가는 값을 보려면 아래 주석을 해제하세요
#      hibernate:
#        type:
#          descriptor:
#            sql: trace